import '../models/codes.dart';
import '../models/patient.dart';
import '../util/localized_text.dart';

/// Twenty fictive patients.
///
/// Every detail here is invented. The national register numbers follow the real
/// Belgian NISS structure, check digits included, so the format-validation
/// exercises have something honest to chew on - but the numbers belong to
/// nobody. Names, addresses, phone numbers and e-mail addresses are fictional;
/// the `example.be` domain is reserved for exactly this purpose.
///
/// The mix is intentional: francophone and Dutch-speaking patients, two
/// children, three patients over eighty, and eight patients carrying allergies
/// so the prescription and dispensing safety checks have something to catch.
final List<Patient> seedPatients = <Patient>[
  Patient(
    id: 'pat-001',
    mrn: 'MRN000001',
    nationalNumber: '48.03.12-057.30',
    familyName: 'Van Damme',
    givenName: 'Émile',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1948, 3, 12),
    address: const Address(
      line: 'Rue de la Loi 42',
      city: 'Bruxelles',
      postalCode: '1000',
    ),
    phone: '+32 2 511 20 34',
    email: 'emile.vandamme@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'O+',
    generalPractitioner: 'Dr. Leroy',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-001-alg-1',
        patientId: 'pat-001',
        substance: const LocalizedText(
          en: 'Penicillin',
          fr: 'Pénicilline',
          nl: 'Penicilline',
        ),
        reaction: const LocalizedText(
          en: 'Urticaria',
          fr: 'Urticaire',
          nl: 'Netelroos',
        ),
        criticality: AllergyCriticality.high,
        recordedDate: DateTime.utc(1953, 3, 12),
      ),
    ],
  ),
  Patient(
    id: 'pat-002',
    mrn: 'MRN000002',
    nationalNumber: '55.07.22-064.92',
    familyName: 'Dupont',
    givenName: 'Marie-Claire',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1955, 7, 22),
    address: const Address(
      line: 'Avenue des Tilleuls 8',
      city: 'Namur',
      postalCode: '5000',
    ),
    phone: '+32 81 22 45 67',
    email: 'mc.dupont@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'A+',
    generalPractitioner: 'Dr. Gilson',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-002-alg-1',
        patientId: 'pat-002',
        substance: const LocalizedText(
          en: 'Iodinated contrast',
          fr: 'Produit de contraste iodé',
          nl: 'Jodiumhoudend contrastmiddel',
        ),
        reaction: const LocalizedText(
          en: 'Anaphylaxis',
          fr: 'Anaphylaxie',
          nl: 'Anafylaxie',
        ),
        criticality: AllergyCriticality.high,
        recordedDate: DateTime.utc(1960, 7, 22),
      ),
      Allergy(
        id: 'pat-002-alg-2',
        patientId: 'pat-002',
        substance: const LocalizedText(en: 'Latex', fr: 'Latex', nl: 'Latex'),
        reaction: const LocalizedText(
          en: 'Contact dermatitis',
          fr: 'Dermatite de contact',
          nl: 'Contactdermatitis',
        ),
        criticality: AllergyCriticality.low,
        recordedDate: DateTime.utc(1960, 7, 22),
      ),
    ],
  ),
  Patient(
    id: 'pat-003',
    mrn: 'MRN000003',
    nationalNumber: '62.11.05-071.91',
    familyName: 'Willems',
    givenName: 'Jan',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1962, 11, 5),
    address: const Address(
      line: 'Lange Nieuwstraat 118',
      city: 'Antwerpen',
      postalCode: '2000',
    ),
    phone: '+32 3 232 11 90',
    email: 'jan.willems@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'B+',
    generalPractitioner: 'Dr. Aerts',
  ),
  Patient(
    id: 'pat-004',
    mrn: 'MRN000004',
    nationalNumber: '78.01.30-078.85',
    familyName: 'Boukhari',
    givenName: 'Fatima',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1978, 1, 30),
    address: const Address(
      line: 'Chaussée de Gand 210',
      city: 'Molenbeek-Saint-Jean',
      postalCode: '1080',
    ),
    phone: '+32 2 414 78 21',
    email: 'f.boukhari@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'O-',
    generalPractitioner: 'Dr. Nassiri',
  ),
  Patient(
    id: 'pat-005',
    mrn: 'MRN000005',
    nationalNumber: '90.05.14-086.61',
    familyName: 'Lemaire',
    givenName: 'Sophie',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1990, 5, 14),
    address: const Address(
      line: 'Rue Saint-Gilles 31',
      city: 'Liège',
      postalCode: '4000',
    ),
    phone: '+32 4 223 56 78',
    email: 'sophie.lemaire@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'AB+',
    generalPractitioner: 'Dr. Renard',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-005-alg-1',
        patientId: 'pat-005',
        substance: const LocalizedText(
          en: 'Peanut',
          fr: 'Arachide',
          nl: 'Pinda',
        ),
        reaction: const LocalizedText(
          en: 'Angioedema',
          fr: 'Œdème de Quincke',
          nl: 'Angio-oedeem',
        ),
        criticality: AllergyCriticality.high,
        recordedDate: DateTime.utc(1995, 5, 14),
      ),
    ],
  ),
  Patient(
    id: 'pat-006',
    mrn: 'MRN000006',
    nationalNumber: '85.09.03-093.16',
    familyName: 'Janssens',
    givenName: 'Lars',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1985, 9, 3),
    address: const Address(
      line: 'Korenlei 15',
      city: 'Gent',
      postalCode: '9000',
    ),
    phone: '+32 9 225 44 12',
    email: 'lars.janssens@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'A-',
    generalPractitioner: 'Dr. De Wilde',
  ),
  Patient(
    id: 'pat-007',
    mrn: 'MRN000007',
    nationalNumber: '01.02.19-100.73',
    familyName: 'Haddad',
    givenName: 'Amina',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(2001, 2, 19),
    address: const Address(
      line: 'Rue Royale 275',
      city: 'Schaerbeek',
      postalCode: '1030',
    ),
    phone: '+32 2 242 33 09',
    email: 'amina.haddad@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'O+',
    generalPractitioner: 'Dr. Nassiri',
  ),
  Patient(
    id: 'pat-008',
    mrn: 'MRN000008',
    nationalNumber: '43.06.27-107.28',
    familyName: 'De Smet',
    givenName: 'Pieter',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1943, 6, 27),
    address: const Address(
      line: 'Steenstraat 62',
      city: 'Brugge',
      postalCode: '8000',
    ),
    phone: '+32 50 33 21 44',
    email: 'pieter.desmet@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'B-',
    generalPractitioner: 'Dr. Vermeersch',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-008-alg-1',
        patientId: 'pat-008',
        substance: const LocalizedText(
          en: 'Acetylsalicylic acid',
          fr: 'Acide acétylsalicylique',
          nl: 'Acetylsalicylzuur',
        ),
        reaction: const LocalizedText(
          en: 'Bronchospasm',
          fr: 'Bronchospasme',
          nl: 'Bronchospasme',
        ),
        criticality: AllergyCriticality.high,
        recordedDate: DateTime.utc(1948, 6, 27),
      ),
    ],
  ),
  Patient(
    id: 'pat-009',
    mrn: 'MRN000009',
    nationalNumber: '68.12.08-114.91',
    familyName: 'Rousseau',
    givenName: 'Camille',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1968, 12, 8),
    address: const Address(
      line: 'Boulevard Tirou 90',
      city: 'Charleroi',
      postalCode: '6000',
    ),
    phone: '+32 71 32 18 55',
    email: 'c.rousseau@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'A+',
    generalPractitioner: 'Dr. Gilson',
  ),
  Patient(
    id: 'pat-010',
    mrn: 'MRN000010',
    nationalNumber: '15.04.21-121.09',
    familyName: 'Vermeulen',
    givenName: 'Noah',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(2015, 4, 21),
    address: const Address(
      line: 'Naamsestraat 44',
      city: 'Leuven',
      postalCode: '3000',
    ),
    phone: '+32 16 22 90 31',
    email: 'ouders.vermeulen@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'O+',
    generalPractitioner: 'Dr. Aerts',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-010-alg-1',
        patientId: 'pat-010',
        substance: const LocalizedText(
          en: 'Cow\'s milk protein',
          fr: 'Protéines de lait de vache',
          nl: 'Koemelkeiwit',
        ),
        reaction: const LocalizedText(
          en: 'Vomiting and rash',
          fr: 'Vomissements et éruption',
          nl: 'Braken en huiduitslag',
        ),
        criticality: AllergyCriticality.low,
        recordedDate: DateTime.utc(2020, 4, 21),
      ),
    ],
  ),
  Patient(
    id: 'pat-011',
    mrn: 'MRN000011',
    nationalNumber: '97.08.16-128.30',
    familyName: 'Martin',
    givenName: 'Élise',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1997, 8, 16),
    address: const Address(
      line: 'Rue de Nimy 12',
      city: 'Mons',
      postalCode: '7000',
    ),
    phone: '+32 65 34 22 78',
    email: 'elise.martin@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'A+',
    generalPractitioner: 'Dr. Renard',
  ),
  Patient(
    id: 'pat-012',
    mrn: 'MRN000012',
    nationalNumber: '72.03.29-135.43',
    familyName: 'Claes',
    givenName: 'Wouter',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1972, 3, 29),
    address: const Address(
      line: 'Koning Albertstraat 27',
      city: 'Hasselt',
      postalCode: '3500',
    ),
    phone: '+32 11 22 66 41',
    email: 'wouter.claes@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'O+',
    generalPractitioner: 'Dr. De Wilde',
  ),
  Patient(
    id: 'pat-013',
    mrn: 'MRN000013',
    nationalNumber: '36.10.02-142.42',
    familyName: 'Legrand',
    givenName: 'Hélène',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1936, 10, 2),
    address: const Address(
      line: 'Rue des Chapeliers 5',
      city: 'Tournai',
      postalCode: '7500',
    ),
    phone: '+32 69 22 14 03',
    email: 'h.legrand@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'AB-',
    generalPractitioner: 'Dr. Leroy',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-013-alg-1',
        patientId: 'pat-013',
        substance: const LocalizedText(
          en: 'Sulfonamides',
          fr: 'Sulfamides',
          nl: 'Sulfonamiden',
        ),
        reaction: const LocalizedText(
          en: 'Stevens-Johnson syndrome',
          fr: 'Syndrome de Stevens-Johnson',
          nl: 'Stevens-Johnsonsyndroom',
        ),
        criticality: AllergyCriticality.high,
        recordedDate: DateTime.utc(1941, 10, 2),
      ),
    ],
  ),
  Patient(
    id: 'pat-014',
    mrn: 'MRN000014',
    nationalNumber: '88.07.11-149.60',
    familyName: 'Amrani',
    givenName: 'Youssef',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1988, 7, 11),
    address: const Address(
      line: 'Rue Wayez 130',
      city: 'Anderlecht',
      postalCode: '1070',
    ),
    phone: '+32 2 523 87 66',
    email: 'y.amrani@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'B+',
    generalPractitioner: 'Dr. Nassiri',
  ),
  Patient(
    id: 'pat-015',
    mrn: 'MRN000015',
    nationalNumber: '59.01.25-156.49',
    familyName: 'Maes',
    givenName: 'Greet',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1959, 1, 25),
    address: const Address(
      line: 'Bruul 88',
      city: 'Mechelen',
      postalCode: '2800',
    ),
    phone: '+32 15 20 33 71',
    email: 'greet.maes@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'A-',
    generalPractitioner: 'Dr. Vermeersch',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-015-alg-1',
        patientId: 'pat-015',
        substance: const LocalizedText(
          en: 'Pollen',
          fr: 'Pollen',
          nl: 'Pollen',
        ),
        reaction: const LocalizedText(
          en: 'Allergic rhinitis',
          fr: 'Rhinite allergique',
          nl: 'Allergische rhinitis',
        ),
        criticality: AllergyCriticality.low,
        recordedDate: DateTime.utc(1964, 1, 25),
      ),
    ],
  ),
  Patient(
    id: 'pat-016',
    mrn: 'MRN000016',
    nationalNumber: '10.11.30-163.29',
    familyName: 'Petit',
    givenName: 'Thomas',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(2010, 11, 30),
    address: const Address(
      line: 'Rue du Pont du Christ 3',
      city: 'Wavre',
      postalCode: '1300',
    ),
    phone: '+32 10 22 44 19',
    email: 'parents.petit@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'O+',
    generalPractitioner: 'Dr. Renard',
  ),
  Patient(
    id: 'pat-017',
    mrn: 'MRN000017',
    nationalNumber: '81.05.07-170.95',
    familyName: 'Vandenbossche',
    givenName: 'Ingrid',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1981, 5, 7),
    address: const Address(
      line: 'Molenstraat 21',
      city: 'Aalst',
      postalCode: '9300',
    ),
    phone: '+32 53 77 12 40',
    email: 'i.vandenbossche@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'A+',
    generalPractitioner: 'Dr. De Wilde',
  ),
  Patient(
    id: 'pat-018',
    mrn: 'MRN000018',
    nationalNumber: '66.09.18-177.53',
    familyName: 'Benali',
    givenName: 'Rachid',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1966, 9, 18),
    address: const Address(
      line: 'Rue Xhavée 47',
      city: 'Verviers',
      postalCode: '4800',
    ),
    phone: '+32 87 33 21 58',
    email: 'r.benali@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'O-',
    generalPractitioner: 'Dr. Leroy',
    allergies: <Allergy>[
      Allergy(
        id: 'pat-018-alg-1',
        patientId: 'pat-018',
        substance: const LocalizedText(
          en: 'Morphine',
          fr: 'Morphine',
          nl: 'Morfine',
        ),
        reaction: const LocalizedText(en: 'Pruritus', fr: 'Prurit', nl: 'Jeuk'),
        criticality: AllergyCriticality.low,
        recordedDate: DateTime.utc(1971, 9, 18),
      ),
    ],
  ),
  Patient(
    id: 'pat-019',
    mrn: 'MRN000019',
    nationalNumber: '93.12.24-184.66',
    familyName: 'De Vos',
    givenName: 'Lotte',
    gender: AdministrativeGender.female,
    birthDate: DateTime.utc(1993, 12, 24),
    address: const Address(
      line: 'Leiestraat 66',
      city: 'Kortrijk',
      postalCode: '8500',
    ),
    phone: '+32 56 22 87 30',
    email: 'lotte.devos@example.be',
    preferredLanguage: 'nl',
    bloodGroup: 'B+',
    generalPractitioner: 'Dr. Vermeersch',
  ),
  Patient(
    id: 'pat-020',
    mrn: 'MRN000020',
    nationalNumber: '51.02.14-191.86',
    familyName: 'Dubois',
    givenName: 'Georges',
    gender: AdministrativeGender.male,
    birthDate: DateTime.utc(1951, 2, 14),
    address: const Address(
      line: 'Rue de Diekirch 9',
      city: 'Arlon',
      postalCode: '6700',
    ),
    phone: '+32 63 22 45 91',
    email: 'georges.dubois@example.be',
    preferredLanguage: 'fr',
    bloodGroup: 'A+',
    generalPractitioner: 'Dr. Gilson',
  ),
];
